name: CMake

on:
  push:
    branches: [ "master" ]
    tags: [ "v0.1" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout main repository with submodules
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        dir: '${{ github.workspace }}/qt/'
        install-deps: 'true'
        setup-python: 'true'
        set-env: 'true'
      
    - name: Install Vulkan SDK
      uses: humbletim/setup-vulkan-sdk@v1.2.0
      with:
        vulkan-query-version: 1.2.170.0
        vulkan-components: Vulkan-Headers, Vulkan-Loader
        vulkan-use-cache: true

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      env:
        SFML_DIR: '${{ github.workspace }}/Library/sfml/lib/cmake/SFML'

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target OpenBus

    - name: Package Release
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'OpenBus-Release-${{github.ref_name}}.zip'
        path: '${{ github.workspace }}/bin/${{env.BUILD_TYPE}}/*'

    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: 'OpenBus-Release-${{github.ref_name}}.zip'
        tag: '${{github.ref_name}}'